### ISSUE TITLE
ctrl+alt+c no longer works

### ISSUE THREAD

**Issue by guyellis** [jacogr/atom-lcov-info#25]
First of all: awesome plugin! I use it frequently.

This could be user error. I just upgraded atom and all plugins and ctrl+alt+c now no longer maps to lcov-info:toggle. If I use ctrl+shift+p I can toggle lcov-info so the functionality is still there. If I look at key binding resolver it lists lcov-info:toggle at the top of the list of 3 items for ctrl+alt+c.

Ideas?

![keybindingresolver](https://cloud.githubusercontent.com/assets/2047725/7936029/8e2fa78e-08ea-11e5-95bd-0a0801a2d6bf.png)

**Comment by Nickersoft** [comment]
@guyellis I can confirm this is a bug. The issue comes from the fact the keybinding is for `.atom-workspace`, when it should just be `atom-workspace`. I tried making the change myself but @jacogr disallows outside contributors from pushing to this repo directly. For now, follow these steps to resolve:

1. Go to Atom Settings
2. Click on "Keybindings"
3. Search for "lcov-info"
4. Click the clipboard icon next to the keybinding
5. Click on the link to "your keymap file" or go to the Atom menu and click "Open Your Keymap"
6. Ctrl+V
7. Remove the leading dot from `.atom-workspace` 
8. Save and reload atom
